name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Necesario para la autenticación OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/856567522150/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@caliope-app-3.iam.gserviceaccount.com'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Asegúrate que sea la versión que usan tus functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install function dependencies
        run: npm --prefix functions install

      - name: Deploy to Firebase
        run: firebase deploy --only functions --project caliope-app-3 --non-interactive
