name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main # Dispara el workflow en cada push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest # Ejecuta el job en una máquina virtual Linux
    permissions:
      contents: 'read'
      id-token: 'write' # ¡Importante para Workload Identity Federation!

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Asegúrate que esta sea la versión de Node.js de tu Next.js (la que elegiste en create-next-app)

      - name: Install dependencies
        run: npm ci # Usa 'npm ci' para instalaciones limpias en CI/CD
        working-directory: app-frontend # Ahora apunta a la subcarpeta de Next.js

      - name: Build Next.js app
        run: npm run build
        working-directory: app-frontend # Ahora apunta a la subcarpeta de Next.js

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/856567522150/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@caliope-app-3.iam.gserviceaccount.com

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase App Hosting
        run: firebase deploy --only hosting --project=caliope-app-3
        # Ya no necesitas repoToken, firebaseServiceAccount, ni projectId aquí
        # porque la autenticación se maneja con Workload Identity Federation
